"""Initial schema based on current models

Revision ID: f5c09aed1e3f
Revises: 
Create Date: 2025-04-14 22:21:40.930735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c09aed1e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_path', sa.String(), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_path')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('pending_email', sa.String(length=120), nullable=True),
    sa.Column('pending_password_hash', sa.String(length=256), nullable=True),
    sa.Column('confirmation_token', sa.String(length=256), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pending_email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_confirmation_token'), ['confirmation_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_confirmation_token'))

    op.drop_table('user')
    op.drop_table('lock')
    op.drop_table('configuration')
    # ### end Alembic commands ###
